name: base_de_test
version: 1.0.0+1
publish_to: none
description: base de test pour app flutter
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  http: 0.13.5
  flutter_riverpod: 2.1.3
  riverpod_annotation: 1.1.1
  dio: 4.0.6
  shared_preferences: 2.0.17
  supabase: 1.4.0
  supabase_flutter: 1.3.1
  go_router: 6.0.2
  freezed: 2.3.2
  json_serializable: 6.6.1
  freezed_annotation: 2.2.0
  fpdart: 0.4.0
  uni_links: 0.5.1
  intl: 0.17.0
  equatable: 2.0.5
  form_validators: 0.3.0
  formz: 0.4.1
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  mockito: 5.3.2
  build_runner: 2.3.3
  riverpod_generator: 1.1.1
  flutter_flavorizr: 2.1.5
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/json/
  uses-material-design: true
  generate: true

