name: base_de_test
version: 1.0.0+1
publish_to: none
description: base de test pour app flutter
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  http: 0.13.5
  flutter_riverpod: 2.1.3
  riverpod_annotation: 1.1.1
  dio: 4.0.6
  shared_preferences: 2.0.17
  supabase: ^1.5.1
  supabase_flutter: ^1.4.0
  go_router: ^6.0.6
  freezed_annotation: 2.2.0
  fpdart: 0.4.0
  uni_links: 0.5.1
  intl: ^0.18.0
  equatable: 2.0.5
  formz: 0.4.1
  sqflite: 2.2.4+1
  flutter_staggered_grid_view: 0.6.2
  path: 1.8.3
  syncfusion_flutter_datepicker: 20.4.51
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  mockito: 5.3.2
  build_runner: ^2.3.3
  riverpod_generator: 1.1.1
  flutter_flavorizr: 2.1.5
  json_serializable: 6.6.1
  freezed: 2.3.2
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/json/
  uses-material-design: true
  generate: true

